# Generated by Django 4.1.2 on 2022-10-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('post', models.TextField(max_length=1000)),
                ('reaction', models.CharField(choices=[('REAC_A', 'Reaction_A'), ('REAC_B', 'Reaction_B'), ('REAC_C', 'Reaction_C')], default=None, max_length=20)),
            ],
        ),
    ]
